### PR TITLE
Cryptography moved from cloudshell-core

### PR DESCRIPTION
**Pull request by igoro1975**
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/cloudshell-shell-core/50)

### CODE REVIEW

**Comment by igoro1975** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/50)*

**Comment by yaroslavNqualisystems** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[cloudshell/shell/core/cryptography/aes_service.py, line 6 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/50#-KZLPvjmJposQ-eOhAGO:-KZLPvjmJposQ-eOhAGP:boqkcrb) ([raw file](https://github.com/qualisystems/cloudshell-shell-core/blob/2f9d43d9b195b690fde59986861169467fd369f4/cloudshell/shell/core/cryptography/aes_service.py#L6)):*
> ```Python
> 
> 
> class AESCipher:
> ```

Please add doc strings!

---

*[cloudshell/shell/core/cryptography/aes_service.py, line 10 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/50#-KZLQ5XYHCXZKWhXP_Ww:-KZLQ5XYHCXZKWhXP_Wx:b-3l0zyo) ([raw file](https://github.com/qualisystems/cloudshell-shell-core/blob/2f9d43d9b195b690fde59986861169467fd369f4/cloudshell/shell/core/cryptography/aes_service.py#L10)):*
> ```Python
>         self.key = base64.b64decode(key)
> 
>     def encrypt(self, raw):
> ```

Docstrings?

---

*[cloudshell/shell/core/cryptography/aes_service.py, line 11 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/50#-KZLPV_MLTgSCX4VdJqb:-KZLPV_MLTgSCX4VdJqc:b-w6b9fi) ([raw file](https://github.com/qualisystems/cloudshell-shell-core/blob/2f9d43d9b195b690fde59986861169467fd369f4/cloudshell/shell/core/cryptography/aes_service.py#L11)):*
> ```Python
> 
>     def encrypt(self, raw):
>         BS = 16
> ```

Constant defined in the method?

---

*[cloudshell/shell/core/cryptography/aes_service.py, line 21 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/50#-KZLQ7B4Eqo61Z71G73G:-KZLOe_Ao9X-A2NH52KV:b-829twl) ([raw file](https://github.com/qualisystems/cloudshell-shell-core/blob/2f9d43d9b195b690fde59986861169467fd369f4/cloudshell/shell/core/cryptography/aes_service.py#L21)):*
>     BS = 16
Docstrings?

---

*[cloudshell/shell/core/cryptography/rsa_service.py, line 13 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/50#-KZLQBnnv2cujcDzzYHG:-KZLQBnnv2cujcDzzYHH:b-3l0zyo) ([raw file](https://github.com/qualisystems/cloudshell-shell-core/blob/2f9d43d9b195b690fde59986861169467fd369f4/cloudshell/shell/core/cryptography/rsa_service.py#L13)):*
> ```Python
> 
>     @staticmethod
>     def read_public_key():
> ```

Docstrings?

---

*[cloudshell/shell/core/cryptography/rsa_service.py, line 19 at r1](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/50#-KZLQEj5SwxGslhcEnXR:-KZLQEj5SwxGslhcEnXS:b-3l0zyo) ([raw file](https://github.com/qualisystems/cloudshell-shell-core/blob/2f9d43d9b195b690fde59986861169467fd369f4/cloudshell/shell/core/cryptography/rsa_service.py#L19)):*
> ```Python
>         return file_object.read()
> 
>     def encrypt(self, input):
> ```

Docstrings?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/50)*

**Comment by igoro1975** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/50)*

**Comment by yaroslavNqualisystems** [comment]
Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/50)*

**Comment by alexazarh** [comment]
Reviewed 4 of 7 files at r1, 2 of 2 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/50)*

**Pull request merged**
