### PR TITLE
added save and restore interfaces

### PR DESCRIPTION
**Pull request by doppleware**
These types are used by the save and restore orchestration standard.

This change is [Reviewable](https://reviewable.io/reviews/qualisystems/cloudshell-shell-core/34)

### CODE REVIEW

**Comment by doppleware** [comment]
Reviewed 10 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/34)*

**Comment by yaroslavNqualisystems** [comment]
Review status: 4 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[cloudshell/shell/core/interfaces/OrchestrationSavedArtifact.py, line 2 \[r3\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/34#-KO4Z1jIFRdlc0iJJ_ML:-KO4Z1jIFRdlc0iJJ_MM:2101078170) ([raw file](https://github.com/qualisystems/cloudshell-shell-core/blob/faba4026e578d149948e53a33aefcb1e545936fb/cloudshell/shell/core/interfaces/OrchestrationSavedArtifact.py#L2)):*
> ```Python
> class OrchestrationSavedArtifact(object):
>     def __init__(self, artifact_type, identifier):
> ```

Why are those clasess interfaces?
Looks like those classes are entities which have some state

---

*[cloudshell/shell/core/interfaces/OrchestrationSavedArtifactsInfo.py, line 1 \[r3\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/34#-KO4Yc7KSXNQjH-Fvz5n:-KO4Yc7KSXNQjH-Fvz5o:-49127184) ([raw file](https://github.com/qualisystems/cloudshell-shell-core/blob/faba4026e578d149948e53a33aefcb1e545936fb/cloudshell/shell/core/interfaces/OrchestrationSavedArtifactsInfo.py#L1)):*
> ```Python
> from cloudshell.shell.core.interfaces.OrchestrationSavedArtifact import OrchestrationSavedArtifact
> ```

Please follow pep8 for file naming

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/34)*

**Comment by doppleware** [comment]
Review status: 4 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[cloudshell/shell/core/interfaces/OrchestrationSavedArtifact.py, line 2 \[r3\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/34#-KO4Z1jIFRdlc0iJJ_ML:-KO6D1MteXi4e_NmhZS_:1316491911) ([raw file](https://github.com/qualisystems/cloudshell-shell-core/blob/faba4026e578d149948e53a33aefcb1e545936fb/cloudshell/shell/core/interfaces/OrchestrationSavedArtifact.py#L2)):*
<details><summary><i>Previously, yaroslavNqualisystems (Yaroslav Nikonorov) wrote…</i></summary>
> Why are those clasess interfaces?
> Looks like those classes are entities which have some state
</details>
They are not interfaces in that sense.. They are just interfaces between the Shell and CloudShell

---

*[cloudshell/shell/core/interfaces/OrchestrationSavedArtifactsInfo.py, line 1 \[r3\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/34#-KO4Yc7KSXNQjH-Fvz5n:-KO6D9vjM6hA4rJxmJ0C:-934205083) ([raw file](https://github.com/qualisystems/cloudshell-shell-core/blob/faba4026e578d149948e53a33aefcb1e545936fb/cloudshell/shell/core/interfaces/OrchestrationSavedArtifactsInfo.py#L1)):*
<details><summary><i>Previously, yaroslavNqualisystems (Yaroslav Nikonorov) wrote…</i></summary>
> Please follow pep8 for file naming
</details>
Renamed. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/34)*

**Comment by doppleware** [comment]
Reviewed 1 of 1 files at r2, 1 of 5 files at r3, 4 of 5 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/34)*

**Comment by doppleware** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cloudshell/shell/core/interfaces/OrchestrationSavedArtifact.py, line 2 \[r3\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/34#-KO4Z1jIFRdlc0iJJ_ML:-KO6DToR9EH3sdrPJwm4:-499146009) ([raw file](https://github.com/qualisystems/cloudshell-shell-core/blob/faba4026e578d149948e53a33aefcb1e545936fb/cloudshell/shell/core/interfaces/OrchestrationSavedArtifact.py#L2)):*
<details><summary><i>Previously, doppleware (Roni Dover) wrote…</i></summary>
> They are not interfaces in that sense.. They are just interfaces between the Shell and CloudShell
</details>
Done.

---

*[cloudshell/shell/core/interfaces/OrchestrationSavedArtifactsInfo.py, line 1 \[r3\]](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/34#-KO4Yc7KSXNQjH-Fvz5n:-KO6DSf84Lel1xeVHq4_:-499146009) ([raw file](https://github.com/qualisystems/cloudshell-shell-core/blob/faba4026e578d149948e53a33aefcb1e545936fb/cloudshell/shell/core/interfaces/OrchestrationSavedArtifactsInfo.py#L1)):*
<details><summary><i>Previously, doppleware (Roni Dover) wrote…</i></summary>
> Renamed. Thanks!
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/cloudshell-shell-core/34)*

**Pull request merged**
